name: Analyze github pull requests
on: workflow_dispatch
jobs:
  github-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: 'Analyze github pull requests'
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          teams: adoption, fe-infra, analytics, data-management, sdk, skylab, cerebro
          team0: sputh, kelvin-lu, TroutZen, albertli88, kelsonpw
          team1: ManThursday
          team2: djih, cely404, RFitz, RFitz
          team3: jackmccloy, rctbusk, shreyvalia1, theoschao, fej-snikduj
          team4: haoliu-amp, jooohhn, dnchn
          team5: davemn
          team6: ricfang
