name: Analyze github pull requests
on: workflow_dispatch
jobs:
  github-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: 'Analyze github pull requests'
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          teams: adoption, fe-infra, analytics, data-management, sdk, skylab, cerebro
          team-adoption: sputh, kelvin-lu, TroutZen, albertli88, kelsonpw
          team-fe-infra: ManThursday
          team-analytics: djih, cely404, RFitz, RFitz
          team-data-mangement: jackmccloy, rctbusk, shreyvalia1, theoschao, fej-snikduj
          team-sdk: haoliu-amp, jooohhn, dnchn
          team-skylab: davemn
          team-cerebro: ricfang
